name: rl-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - setuptools==65.5.0
      - wheel==0.38.0
      - numpy<2.0
      - nes_py
      - gym-super-mario-bros==7.3.0
      - torch
      - torchvision
      - torchaudio
      - stable-baselines3==2.0.0